/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-27 04:15:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1663044204173L));
    _jspx_dependants.put("jar:file:/C:/Users/sungw/springRaelProject/raelproject3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/rael/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/style.css\">\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Insert title here</title>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<h1>Responsive Table</h1>\r\n");
      out.write("  <table class=\"rwd-table\">\r\n");
      out.write("    <tbody>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th>Supplier Code</th>\r\n");
      out.write("        <th>Supplier Name</th>\r\n");
      out.write("        <th>Invoice Number</th>\r\n");
      out.write("        <th>Invoice Date</th>\r\n");
      out.write("        <th>Due Date</th>\r\n");
      out.write("        <th>Net Amount</th>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td data-th=\"Supplier Code\">\r\n");
      out.write("          UPS5005\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Supplier Name\">\r\n");
      out.write("          UPS\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Invoice Number\">\r\n");
      out.write("          ASDF19218\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Invoice Date\">\r\n");
      out.write("          06/25/2016\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Due Date\">\r\n");
      out.write("          12/25/2016\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Net Amount\">\r\n");
      out.write("          $8,322.12\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td data-th=\"Supplier Code\">\r\n");
      out.write("          UPS3449\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Supplier Name\">\r\n");
      out.write("          UPS South Inc.\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Invoice Number\">\r\n");
      out.write("          ASDF29301\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Invoice Date\">\r\n");
      out.write("          6/24/2016\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Due Date\">\r\n");
      out.write("          12/25/2016\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Net Amount\">\r\n");
      out.write("          $3,255.49\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td data-th=\"Supplier Code\">\r\n");
      out.write("          BOX5599\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Supplier Name\">\r\n");
      out.write("          BOX Pro West\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Invoice Number\">\r\n");
      out.write("          ASDF43000\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Invoice Date\">\r\n");
      out.write("          6/27/2016\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Due Date\">\r\n");
      out.write("          12/25/2016\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Net Amount\">\r\n");
      out.write("          $45,255.49\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td data-th=\"Supplier Code\">\r\n");
      out.write("          PAN9999\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Supplier Name\">\r\n");
      out.write("          Pan Providers and Co.\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Invoice Number\">\r\n");
      out.write("          ASDF33433\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Invoice Date\">\r\n");
      out.write("          6/29/2016\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Due Date\">\r\n");
      out.write("          12/25/2016\r\n");
      out.write("        </td>\r\n");
      out.write("        <td data-th=\"Net Amount\">\r\n");
      out.write("          $12,335.69\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("  <h3>Resize Me</h3>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
